modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/Th0mas-7/SimplyJetpacks3/issues"

[[mods]]
modId="simplyjetpacks"
version="${file.jarVersion}"
displayName="Simply Jetpacks 3"
updateJSONURL="https://github.com/Th0mas-7/SimplyJetpacks3/blob/master/updates/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/simply-jetpacks-3"
logoFile="simplyjetpacks.png"
credits="cybercat5555"
authors="StormedPanda"
description='''
Simply Jetpacks 3 Description

Previous Authors: Tomson124, tonius11
'''

[[dependencies.simplyjetpacks]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.simplyjetpacks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
